### PR TITLE
Feat: persist wallet in local storage

### PR DESCRIPTION
**Pull request by phips28**
Will automatically reconnect with wallet after browser reload.

I could only test this with MathWallet.

### CODE REVIEW

**Comment by axeldelamarre** [comment]
Please merge this

**Comment by phips28** [comment]
@edsolater @TimonPeng @rudy5348 can you please have a look and merge please?

**Comment by TimonPeng** [comment]
Thanks a lot for your cooperation! We made that few days ago so I closed this pr.

**Comment by phips28** [comment]
@TimonPeng I saw this already in the frontend :) cool.
But most of the time after a reload it throws en error, because the mathwallet extension is not initialized. Thats why I added those sleep on failure, and retry some times.

**Pull request closed without merging**
