### PR TITLE
"to" value can be updated and converted to "from"

### PR DESCRIPTION
**Pull request by Illyism**
https://www.loom.com/share/b79885cbf6ea42de92ee388a145395f7

Hey there! I noticed it's a bit annoying to have to calculate the price if you want to think in the "to" coin price. So I made it so that both inputs in the swap are editable.

### CODE REVIEW

**Comment by TimonPeng** [comment]
Thanks for the contribution!

**Comment by phips28** [comment]
Awesome! waited for this already! 🙂

**Comment by phips28** [comment]
why was this reverted? 
https://github.com/raydium-io/raydium-ui/commit/b87ac085ec7239562940fc761e6f9e277c2426b7

**Comment by TimonPeng** [comment]
Input mount will error if you try to change side many times, no time to found why this time, sorry for that.

**Comment by Illyism** [comment]
@TimonPeng let me know what can be improved!

**Comment by Illyism** [comment]
@TimonPeng will investigate. Is it a console error?

**Comment by TimonPeng** [comment]
The trading volume at transaction will be much larger, i guess is ratio problem

**Comment by TimonPeng** [comment]
You can try to use SOL/RAY swap, and change side many times, you can see the amount in transaction will be much larger.

**Pull request merged**
